# Generated by Django 3.1.7 on 2021-04-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=60)),
                ('description', models.TextField(default='Description text')),
                ('poster_v', models.ImageField(upload_to='media/images')),
                ('poster_h', models.ImageField(upload_to='media/images')),
                ('trailer', models.CharField(max_length=1000)),
                ('duration', models.IntegerField()),
                ('certification', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
