# Generated by Django 3.1.7 on 2021-04-13 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, related_name='show_movie', to='accounts.movie'),
            preserve_default=False,
        ),
    ]
