# Generated by Django 3.1.7 on 2021-04-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_show_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2001-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(default='2001-12-31', null=True),
        ),
    ]
