# Generated by Django 3.1.7 on 2021-04-13 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='show_theatre', to='accounts.theatre'),
            preserve_default=False,
        ),
    ]
