# Generated by Django 3.1.7 on 2021-04-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_show_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_h',
            field=models.ImageField(upload_to='poster_h'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_v',
            field=models.ImageField(upload_to='poster_v'),
        ),
    ]
