# Generated by Django 3.1.7 on 2021-04-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210413_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='show',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
        migrations.DeleteModel(
            name='show',
        ),
        migrations.DeleteModel(
            name='theatre',
        ),
    ]
