# Generated by Django 3.1.7 on 2021-04-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=60)),
                ('description', models.TextField(default='Description text')),
                ('poster_v', models.ImageField(upload_to='poster_v')),
                ('poster_h', models.ImageField(upload_to='poster_h')),
                ('trailer', models.CharField(max_length=1000)),
                ('duration', models.IntegerField()),
                ('release_date', models.DateField(default='2001-12-31', null=True)),
                ('certification', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2001-12-31', null=True)),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_movie', to='movies.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_theatre', to='movies.theatre')),
            ],
        ),
    ]
