# Generated by Django 3.1.7 on 2021-04-18 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20210414_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='show',
            name='theatre',
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_show', to='movies.show')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_theatre', to='movies.theatre')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
