# Generated by Django 3.1.7 on 2021-04-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210418_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='seating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('column', models.PositiveSmallIntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Available'), (2, 'Booked')], default=1)),
            ],
        ),
    ]
