# Generated by Django 3.1.7 on 2021-04-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210418_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seating',
            name='user',
        ),
    ]
