# Generated by Django 3.1.7 on 2021-04-18 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0009_remove_seating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
