# Generated by Django 3.2 on 2021-04-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_seating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seating',
            name='column',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='row',
        ),
        migrations.AddField(
            model_name='seating',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seat_booking', to='movies.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seating',
            name='name',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
