# Generated by Django 3.2 on 2021-04-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210419_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seating',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='name',
        ),
        migrations.AddField(
            model_name='seating',
            name='column',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seating',
            name='row',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
