# Generated by Django 3.2 on 2021-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20210419_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seating',
            name='column',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='row',
        ),
        migrations.AddField(
            model_name='seating',
            name='name',
            field=models.CharField(default='A1', max_length=4),
            preserve_default=False,
        ),
    ]
