# Generated by Django 3.2 on 2021-04-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20210419_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='seating',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_booking', to='movies.booking'),
        ),
    ]
