# Generated by Django 3.1.7 on 2021-04-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_seating_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seating',
            name='user',
        ),
    ]
